### ISSUE TITLE
Parsing a Date from an empty string slice panics

### ISSUE THREAD

**Issue by nazar554** [time-rs/time#215]
Cargo.toml:
```
time = "0.2.6"
```

Code:
```rust
fn main() {
    time::Date::parse("", "%d.%m.%Y");
}
```
Output:
```
thread 'main' panicked at 'byte index 2 is out of bounds of ``', src\libcore\str\mod.rs:2052:9
stack backtrace:
   0:     0x7ff6db922ae9 - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1:     0x7ff6db922ae9 - std::sys_common::backtrace::_print_fmt
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:84
   2:     0x7ff6db922ae9 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:61
   3:     0x7ff6db931c3b - core::fmt::write
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\fmt\mod.rs:1025
   4:     0x7ff6db91fe64 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\io\mod.rs:1426
   5:     0x7ff6db9252e9 - std::sys_common::backtrace::_print
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:65
   6:     0x7ff6db9252e9 - std::sys_common::backtrace::print
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:50
   7:     0x7ff6db9252e9 - std::panicking::default_hook::{{closure}}
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:193
   8:     0x7ff6db924f3c - std::panicking::default_hook
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:210
   9:     0x7ff6db925a8c - std::panicking::rust_panic_with_hook
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:471
  10:     0x7ff6db925610 - std::panicking::begin_panic_handler
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:375
  11:     0x7ff6db92e96d - core::panicking::panic_fmt
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\panicking.rs:84
  12:     0x7ff6db930181 - core::str::slice_error_fail
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\str\mod.rs:0
  13:     0x7ff6db9395f0 - core::str::traits::{{impl}}::index::{{closure}}
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\str\mod.rs:1856
  14:     0x7ff6db7bd4e1 - core::option::Option<str*>::unwrap_or_else<str*,closure-0>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\option.rs:422
  15:     0x7ff6db7caf38 - core::str::traits::{{impl}}::index
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\str\mod.rs:1856
  16:     0x7ff6db9396a7 - core::str::traits::{{impl}}::index<core::ops::range::RangeTo<usize>>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\str\mod.rs:1658
  17:     0x7ff6db7bc8d3 - time::format::parse::try_consume_exact_digits<u8>
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.2.6\src\format\parse.rs:299
  18:     0x7ff6db78b3de - time::format::parse::parse
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.2.6\src\format\parse.rs:356
  19:     0x7ff6db7b6a4b - time::date::Date::parse
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.2.6\src\date.rs:929
  20:     0x7ff6db7b6a4b - example::main
```

**Comment by jhpratt** [comment]
Taking a look into this. It's trivial to fix, but getting the right error output is not so much.

**Comment by jhpratt** [comment]
Actually, the trivial fix gives an error consistent with other situations. Pushing changes up. It'll be out in a 0.2.7 release, which should come relatively soon (just pending reviews over on #203).

**Comment by jhpratt** [comment]
Well, looks like that change actually breaks some other things.

**Comment by jhpratt** [comment]
Gotta love off-by-one errors :smile:
