### ISSUE TITLE
Negating `Duration::MIN` panics with negating overflow in 0.3.0-alpha-2

### ISSUE THREAD

**Issue by timvisee** [time-rs/time#340]
Negating `Duration::MIN` currently overflows in `v0.3.0-alpha-2`.

```rust
-Duration::MIN
```

```
thread 'main' panicked at 'attempt to negate with overflow', /home/timvisee/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.3.0-alpha-2/src/duration.rs:810:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   3: <time::duration::Duration as core::ops::arith::Neg>::neg
             at /home/timvisee/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.3.0-alpha-2/src/duration.rs:810:29
   4: testproject::main
             at ./src/main.rs:4:13
   5: core::ops::function::FnOnce::call_once
             at /home/timvisee/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Is this expected/desired behavior? It doesn't seem to be explicitly stated in the documentation.

cc https://github.com/time-rs/time/issues/248

**Comment by jhpratt** [comment]
What other behavior would there be? It _does_ overflow as stated. If you want to handle that case specifically, `foo.checked_mul(-1)` will work.

**Comment by timvisee** [comment]
Thanks for responding so quickly.

That's a good point. I was wondering (without looking into the internals) whether an overflow was desired in this case. But I guess there's no real way to properly represent the negated value.

Thanks for suggesting `foo.checked_mul(-1)`!
